export const Actions = {
    GET_PRODUCTS: "GET_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    EXISTING_CART: "EXISTING_CART",
    GET_CURRENT_PATH: "GET_CURRENT_PATH"
}